# Generated by Django 3.2.9 on 2022-03-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Character Assessment',
                'verbose_name_plural': 'Character Assessment',
            },
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('FULL PAID', 'COMPLETE'), ('PARTIAL PAID', 'PARTIAL PAID'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='StudentCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[(' D', 'D'), (' C', 'C'), (' A', 'A'), (' F', 'F'), (' B', 'B')], max_length=30, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('remark', models.CharField(max_length=45)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRS.registration')),
            ],
            options={
                'verbose_name': 'Character Assessment',
                'verbose_name_plural': 'Character Assessment',
            },
        ),
    ]
