# Generated by Django 3.2.9 on 2022-03-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0002_auto_20220321_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Character Assessment Item', 'verbose_name_plural': 'Character Assessment Item'},
        ),
        migrations.AlterModelOptions(
            name='studentcharacter',
            options={'verbose_name': 'Student Character Assessment', 'verbose_name_plural': 'Student Character Assessment'},
        ),
        migrations.AddField(
            model_name='studentcharacter',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SRS.character'),
        ),
        migrations.AlterField(
            model_name='studentcharacter',
            name='grade',
            field=models.CharField(choices=[(' D', 'D'), (' B', 'B'), (' F', 'F'), (' C', 'C'), (' A', 'A')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='code',
            field=models.CharField(choices=[('OC', 'Development Cost'), ('EC', 'Direct Cost')], default='EC', max_length=45),
        ),
    ]
