# Generated by Django 3.2.9 on 2022-03-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0003_auto_20220322_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcharacter',
            name='code',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='name',
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('PARTIAL PAID', 'PARTIAL PAID'), ('FULL PAID', 'COMPLETE')], default='NOT PAID', max_length=30, unique=True),
        ),
    ]
