# Generated by Django 3.2.9 on 2022-03-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0004_auto_20220322_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('PARTIAL PAID', 'PARTIAL PAID'), ('FULL PAID', 'COMPLETE'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentcharacter',
            name='grade',
            field=models.CharField(choices=[(' C', 'C'), (' B', 'B'), (' A', 'A'), (' D', 'D'), (' F', 'F')], max_length=30),
        ),
    ]
