# Generated by Django 3.2.9 on 2022-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0006_auto_20220322_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcharacter',
            name='grade',
            field=models.CharField(choices=[('F', 'F'), ('D', 'D'), ('A', 'A'), ('C', 'C'), ('B', 'B')], max_length=30),
        ),
        migrations.AlterField(
            model_name='type',
            name='code',
            field=models.CharField(choices=[('OC', 'Development Cost'), ('EC', 'Direct Cost')], default='EC', max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='coordinator',
            unique_together={('staff', 'rank')},
        ),
    ]
