# Generated by Django 3.2.9 on 2022-03-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0008_auto_20220323_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='remark',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('PARTIAL PAID', 'PARTIAL PAID'), ('FULL PAID', 'COMPLETE'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentcharacter',
            name='grade',
            field=models.CharField(choices=[('D', 'D'), ('C', 'C'), ('B', 'B'), ('F', 'F'), ('A', 'A')], max_length=30),
        ),
        migrations.AlterField(
            model_name='type',
            name='code',
            field=models.CharField(choices=[('EC', 'Direct Cost'), ('OC', 'Development Cost')], default='EC', max_length=45),
        ),
    ]
