# Generated by Django 3.2.9 on 2022-03-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0009_auto_20220324_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('FULL PAID', 'COMPLETE'), ('PARTIAL PAID', 'PARTIAL PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentcharacter',
            name='grade',
            field=models.CharField(choices=[('B', 'B'), ('A', 'A'), ('D', 'D'), ('F', 'F'), ('C', 'C')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='yearresult',
            unique_together={('registration', 'event')},
        ),
    ]
