# Generated by Django 3.2.9 on 2022-03-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0010_auto_20220324_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcharacter',
            name='grade',
            field=models.CharField(choices=[('C', 'C'), ('F', 'F'), ('B', 'B'), ('D', 'D'), ('A', 'A')], max_length=30),
        ),
        migrations.AlterField(
            model_name='yearresult',
            name='division',
            field=models.CharField(default='-', editable=False, max_length=12),
        ),
    ]
