# Generated by Django 3.2.9 on 2022-04-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0011_auto_20220325_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('FULL PAID', 'COMPLETE'), ('PARTIAL PAID', 'PARTIAL PAID'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcharacter',
            name='grade',
            field=models.CharField(choices=[('B', 'B'), ('D', 'D'), ('A', 'A'), ('F', 'F'), ('C', 'C')], max_length=30),
        ),
    ]
