from .index import *
from .subject_list import *
from .student_entry import *
from .academic_event_list import *
from .student_academic_year import *
from .combination_subject import *
from .coordinator_and_teacher_classes import *
from .class_subject_assessment import *
from .download_template import *
from .download_admitted_student import *
from .upload import *
from .subject_result import *
from .home import *
from .event_result import *
from .student_registration import *
from .registration_setting import *
from .rank_event_results import *
from .coordinator_classes_combination import *
from .download_registration_template import *
from .cron_job import *
from .handler500 import *
from .coordinator_classes_results import *
from .coordinator_classes_combination_results import *
from .download_result import *
from .send_event_result import *
from .send_sms_api import *
from .download_csv_result import *
from .delete_subject_result import *
from .finance_views import *
from .auto_complete_views import *
